### ISSUE TITLE
[thanks] This looks very useful for my tax needs

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-API6#6]
David, thanks for all your tremendous work in this area! 

I have seen your module updats reported from CPAN on #raku often and didn't think I had any use for them. I have been generating PostScript files by hand and Perl and now Raku for over 25 years and started converting the PS to pdf as soon as ps2pdf came along.

However, this year I see how your modules can help me greatly! This year, for the first time ever, I signed on with a local CPA so my wife can have financial help in the event of my demise.

He requires us to fill out detailed pdf forms so he can have controlled input for his work flow. Today, while wrestling with some tax stuff for him, I find that it would be nice if I can programmatically update some or all of his 16-page pdf form from my records via Raku filtering from csv dumps from our financial accounts. With the help of your wonderful modules I hope to have some success soon!

Blessings.

-Tom (@tbrowder)

**Comment by dwarring** [comment]
Hi Tom,
I also came to PDF from PostScript. Was using it extensively in a mail-house before moving to a PDF based print operation.

Hope that Raku and the PDF modules can help take the pain our of form-filling. Let me know how you go.
- David

**Comment by tbrowder** [comment]
On Wed, Apr 8, 2020 at 12:48 David Warring <notifications@github.com> wrote:

> Hi Tom,
> I also came to PDF from PostScript. Was using it extensively in a
> mail-house before moving to a PDF based print operation.
>
> Hope that Raku and the PDF modules can help take the pain our of
> form-filling. Let me know how you go.
>

Thanks, David. I have to admit I'm looking to see what 'pdftk' can do at
the moment. I'm wrapping it in Raku mainly to encapsulate my desired ops
and simplify the awkward CLI with its many ops.

A demo prog for grabbing form data and filling them in on your Github
account would be very helpful.

**Comment by dwarring** [comment]
Hi Tom,
I added examples/pdf-fields.raku to the repo with the last commit. Happened to have a script that I adapted unreleased module https://github.com/p6-pdf/FDF-p6

Usage is:

-  `pdf-fields.raku --list <pdf>` - to list fields
-  `pdf-fields.raku --fill key val [key2 val2 ...] <pdf>`  - to populate fields

Based on `fillpdffields.pl` from the Perl CAM::PDF module. Which is doing a bit more with setting up field appearances. 

Probably only works on text fields at the moment. Might also have more to do if CAM::PDF is doing a better job. It doing work on setting up field appearances that I have ported yet.

**Comment by tbrowder** [comment]
On Wed, Apr 8, 2020 at 4:25 PM David Warring <notifications@github.com> wrote:
> I added examples/pdf-fields.raku to the repo with the last commit. Happened to have a script that I adapted unreleased module https://github.com/p6-pdf/FDF-p6

David, good timing! 'pdftk' so far isn't helping a lot. I can see the
fields but no easy way to correlate fields with what's on the page.

However, the good news is my accountant said they use the data
manually (surely he could use appropriate software, but this way I
guess his billable hours are more ;-D).
Your existing programs I think can let me overwrite the form without
any major problems after I get the page measurements down ok.

But I will try the ones you referenced first--thanks so much!

I hope you and yours didn't suffer during the recent fires down under.

Best regards,

-Tom

P.S. Is Damian Conway anywhere near you?

**Comment by dwarring** [comment]
Thanks Tom,
This PDF is useful as an example and I'm still working through it.

It illustrates the point that sometimes fields are laid out in rows and columns, and don't have useful labels. I.e. that script isn't the right approach. Could be that processing fields in tab order would work better.

Agree it's a mute point if its being manual copied! Hope they're at least cutting and pasting.

I've moved from Australia to the South Island of New Zealand, so wasn't affected by the fires this time. We're both far south.
- David

**Comment by dwarring** [comment]
PS was living in Melbourne when in Aussie, so near Damien, who held some interesting talks at Melbourne PM group.

**Comment by dwarring** [comment]
Have done some more experimentation on this. I can see what CAM::PDF is doing and why. It's not just a matter of setting the form value. The API also needs to rebuild the appearance dictionary (AP) for the updated values to display reliably.
More work needed, I've raised https://github.com/p6-pdf/PDF-API6/issues/7

**Comment by dwarring** [comment]
Hi Tom,
I've come up with a quick solution for populating form fields when the fields are arranged in a table. The fields are ordered left to right from top to bottom.

I needed to fix a bug in PDF::Class fields() method, so please upgrade to 0.4.3.

This script also sets a `NeedAppearances` flag and clears the field appearances (AP).  I need to do this to ensure the updated values are displayed.
```
use PDF::API6;
use PDF::Field;
use PDF::Class:ver<0.4.3+>;

sub clear-fields-display($pdf) {
    # remove displayed values (Appearence) for each field
    .<AP>:delete for $pdf.fields;
    # dynamically display field appreances instead
    $pdf.Root.AcroForm.NeedAppearances = True;
}

sub MAIN($pdf-file, $save-as, Bool :$rebuild) {
    note "opening: $pdf-file";
    my PDF::API6 $pdf .= open: $pdf-file;

    note "clearing fields...";
    clear-fields-display($pdf);

    note "setting fields...";
    constant ColumnsPerRow = 5;
    my @page-fields = $pdf.page(1).fields;
    my $rows = @page-fields.elems div ColumnsPerRow;
    my @table-fields[$rows; ColumnsPerRow] Z= @page-fields;

    my $j = 0;
    for 1 .. $rows -> $row {
        for 1 .. ColumnsPerRow {
            @table-fields[$row-1; $_-1].V = "Row $row Col $_";
        }
    }

    with $save-as {
        note "saving: $_";
        $pdf.save-as($_, :$rebuild);
    }
    else {
        note "updating...";
        $pdf.update;
    }
}
```

**Comment by tbrowder** [comment]
On Mon, Apr 13, 2020 at 18:09 David Warring <notifications@github.com>
wrote:

> Hi Tom,
> I've come up with a quick solution for populating form fields when the
> fields are arranged in a table. The fields are ordered left to right from
> top to bottom.
>
Thanks, David!

-Tom
