### ISSUE TITLE
Explain what the "codes" are in the various tables in file README.md

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/PDF-API6#9]
Are the "codes" aliases for accessors and methods? I hope so because I'm going to try them.

**Comment by dwarring** [comment]
Yes the README just starts using them without introduction. Other than that they're listed in the appendix, but without explanation or background.

In the meantime just try them. Sometimes context matters, e.g. WordSpacing can only be set in a text block `$gfx.text {...}`. 

You should get a 'invalid context` warning, if operators or variables or graphics operations are used incorrectly.

**Comment by tbrowder** [comment]
On Wed, Jan 13, 2021 at 4:35 PM David Warring <notifications@github.com> wrote:
> Yes the README just starts using them without introduction. Other than that they're
...

Thanks!

**Comment by dwarring** [comment]
I've added more explanation on the various codes with 7f1ba91ffd611fd73d5d9abe9f8500c2eaf9bac7.

**Comment by tbrowder** [comment]
On Tue, Jan 19, 2021 at 15:56 David Warring <notifications@github.com>
wrote:

> I've added more explanation on the various codes with 7f1ba91
> <https://github.com/pdf-raku/PDF-API6/commit/7f1ba91ffd611fd73d5d9abe9f8500c2eaf9bac7>
> .
>

Thanks, David.

**Comment by tbrowder** [comment]
I consider this closed, docs are much better.
